#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-layer.schema.json
parent = "core/debian-bookworm"

recipes = [
    # default tedge packages
    "tedge-rugix-core/defaults",

    # containers
    "tedge-rugix-core/docker",

    # Setup the network
    "tedge-rugix-core/setup-network",

    # PKCS11 tools
    "tedge-rugix-core/setup-pkcs11",

    # SBOM
    "rugix-extra/simple-sbom",

    "tedge-config",
    "user-packages",
]
